name: menu2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  bloc: ^9.0.0
  equatable: ^2.0.0
  freezed_annotation: ^3.1.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.1.0


flutter:


  uses-material-design: true

